name: Lint Awesome List

on:
  push:
  pull_request:

jobs:
  awesome-lint:
    name: "lint: awesome-lint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Run awesome-lint
        run: |
          npm install --global awesome-lint@latest
          awesome-lint ./README.md